controller:
  service:
    type: LoadBalancer
    loadBalancerIP: "WEB_IP"
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-ipv4: "WEB_IP"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "_SUBNET_"
    externalTrafficPolicy: Local
    internalTrafficPolicy: Cluster
    allocateLoadBalancerNodePorts: true
  enableSnippets: true
